<?php
$z[0]=Array("id","",15,26);
$z[1]=Array("title","",44,58);
$z[2]=Array("intro","",82,96);
$z[3]=Array("path","",118,131);
$z[4]=Array("director","",153,170);
$z[5]=Array("actor","",189,203);
$z[6]=Array("type","",221,234);
$z[7]=Array("years","",254,268);
$z[8]=Array("rtsp","",286,299);
$z[9]=Array("tv_poster_path1","",329,353);
$z[10]=Array("tv_poster_path2","",392,416);
$z[11]=Array("area","",437,450);
$z[12]=Array("grade","",468,482);

?>