<?php
$z[0]=Array("en","",16,27);
$z[1]=Array("title","",40,54);
$z[2]=Array("intro","",73,87);
$z[3]=Array("demosrc","",104,120);
$z[4]=Array("director","",137,154);
$z[5]=Array("actor","",168,182);
$z[6]=Array("type","",195,208);
$z[7]=Array("redate","",223,238);
$z[8]=Array("rtsp","",251,264);
$z[9]=Array("poster","",279,294);
$z[10]=Array("bigposter","",315,333);
$z[11]=Array("area","",346,359);
$z[12]=Array("grade","",372,386);
$z[13]=Array("other","",400,414);

?>