<?php
$z[0]=Array("id","",16,27);
$z[1]=Array("title","",40,54);
$z[2]=Array("intro","",73,87);
$z[3]=Array("path","",104,117);
$z[4]=Array("director","",134,151);
$z[5]=Array("actor","",165,179);
$z[6]=Array("type","",192,205);
$z[7]=Array("years","",220,234);
$z[8]=Array("rtsp_url","",247,264);
$z[9]=Array("tv_poster_path1","",279,303);
$z[10]=Array("tv_poster_path2","",324,348);
$z[11]=Array("area","",361,374);
$z[12]=Array("grade","",387,401);

?>