<?php
$z[0]=Array("title","",37,51);
$z[1]=Array("intro","",70,84);
$z[2]=Array("path","",101,114);
$z[3]=Array("director","",131,148);
$z[4]=Array("actor","",162,176);
$z[5]=Array("type","",189,202);
$z[6]=Array("years","",217,231);
$z[7]=Array("rtsp","",244,257);
$z[8]=Array("tv_poster_path1","",272,296);
$z[9]=Array("tv_poster_path2","",317,341);
$z[10]=Array("area","",354,367);
$z[11]=Array("grade","",380,394);

?>