
<field:grade itemname="评分" autofield="1" notsend="0" type="int" isnull="true" islist="0" default="50"  maxlength="250" page="">
</field:grade>


<field:director itemname="导演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:director>

<field:actor itemname="演员" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:actor>

<field:years itemname="发布日期" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:years>

<field:runtime itemname="时长" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:runtime>

<field:intro itemname="影片描述" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:intro>

<field:path itemname="试看内容" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:path>

<field:type itemname="类型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:type>

<field:area itemname="地区" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:area>

<field:rtsp_url itemname="rtsp地址" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:rtsp_url>

<field:tv_poster_path1 itemname="电视海报1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tv_poster_path1>


<field:tv_poster_path2 itemname="电视海报2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tv_poster_path2>


<field:tv_poster_path3 itemname="电视海报3" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tv_poster_path3>

<field:tv_poster_path4 itemname="电视海报4" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tv_poster_path4>

<field:mb_poster_path1 itemname="手机海报1" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:mb_poster_path1>

<field:mb_poster_path2 itemname="手机海报2" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:mb_poster_path2>

<field:mb_poster_path3 itemname="手机海报3" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:mb_poster_path3>

<field:mb_poster_path4 itemname="手机海报4" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:mb_poster_path4>
