
<field:grade itemname="评分" autofield="1" notsend="0" type="int" isnull="true" islist="0" default="50"  maxlength="250" page="">
</field:grade>


<field:director itemname="导演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:director>

<field:actor itemname="演员" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:actor>

<field:years itemname="发布日期" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:years>

<field:runtime itemname="时长" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:runtime>

<field:intro itemname="影片描述" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:intro>

<field:path itemname="试看内容" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:path>

<field:type itemname="类型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:type>

<field:area itemname="地区" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:area>
