<?php
$z[0]=Array("global","",397,424);
$z[0][4]['name']="cfg_filebase";
$z[1]=Array("global","",530,557);
$z[1][4]['name']="cfg_filebase";
$z[2]=Array("global","",633,660);
$z[2][4]['name']="cfg_filebase";
$z[3]=Array("global","",724,751);
$z[3][4]['name']="cfg_filebase";
$z[4]=Array("arclist","\r\n        <li class=\"\"><a class=\"links\" data-id=\"[field:id/]\" href=\"[field:arcurl/]\"><img alt=\"\"  class=\"js-v-img\" data-src=\"[field:mb_poster_path2/]\"/></a></li>\r\n        ",984,1362);
$z[4][4]['addfields']="intro,path,director,actor,type,years,rtsp_url,mb_poster_path1,mb_poster_path2,area,grade";
$z[4][4]['row']="3";
$z[4][4]['titlelen']="24";
$z[4][4]['orderby']="pubdate";
$z[4][4]['typeid']="10";
$z[4][4]['idlist']="";
$z[4][4]['channelid']="17";
$z[5]=Array("arclist","\r\n         <li><a class=\"links\" data-id=\"[field:id/]\" href=\"[field:arcurl/]\"><img data-src=\"[field:mb_poster_path1/]\" class=\"js-v-img\"><h3>[field:title/]</h3></a></li>\r\n         ",1562,1947);
$z[5][4]['addfields']="intro,path,director,actor,type,years,rtsp_url,mb_poster_path1,mb_poster_path2,area,grade";
$z[5][4]['row']="3";
$z[5][4]['titlelen']="24";
$z[5][4]['orderby']="pubdate";
$z[5][4]['typeid']="11";
$z[5][4]['idlist']="";
$z[5][4]['channelid']="17";
$z[6]=Array("arclist","\r\n        <li><a class=\"links\" data-id=\"[field:id/]\" href=\"[field:arcurl/]\"><img data-src=\"[field:mb_poster_path1/]\" class=\"js-v-img\"><h3>[field:title/]</h3></a></li>\r\n        ",2147,2530);
$z[6][4]['addfields']="intro,path,director,actor,type,years,rtsp_url,mb_poster_path1,mb_poster_path2,area,grade";
$z[6][4]['row']="3";
$z[6][4]['titlelen']="24";
$z[6][4]['orderby']="pubdate";
$z[6][4]['typeid']="12";
$z[6][4]['idlist']="";
$z[6][4]['channelid']="17";
$z[7]=Array("global","",2571,2598);
$z[7][4]['name']="cfg_filebase";
$z[8]=Array("global","",3597,3626);
$z[8][4]['name']="cfg_nav_server";

?>