<?php
$z[0]=Array("global","",196,223);
$z[0][4]['name']="cfg_filebase";
$z[1]=Array("global","",1511,1538);
$z[1][4]['name']="cfg_filebase";
$z[2]=Array("arclist","\r\n{\r\n	        id:\"[field:id/]\",\r\n			name:\"[field:title/]\",\r\n			movieintro:\"[field:intro/]\",\r\n			videosrc:\"[field:path/]\",\r\n			director:\"[field:director/]\",\r\n			actor:\"[field:actor/]\",\r\n			type:\"[field:type/]\",\r\n			ondata:\"[field:years function=\"MyDate('Y-m-d',@me)\"/]\",\r\n			rstp:\"[field:rtsp_url/]\",\r\n			poster:\"[field:tv_poster_path1/]\",\r\n			sliderposter:\"[field:tv_poster_path2/]\",\r\n			area:\"[field:area/]\",\r\n			star:\"[field:grade/]\"\r\n		},\r\n",1605,2243);
$z[2][4]['addfields']="intro,path,director,actor,type,years,rtsp_url,tv_poster_path1,tv_poster_path2,area,grade";
$z[2][4]['row']="3";
$z[2][4]['titlelen']="24";
$z[2][4]['orderby']="pubdate";
$z[2][4]['idlist']="";
$z[2][4]['channelid']="17";
$z[3]=Array("global","",2295,2322);
$z[3][4]['name']="cfg_filebase";
$z[4]=Array("global","",3247,3274);
$z[4][4]['name']="cfg_filebase";
$z[5]=Array("global","",3319,3346);
$z[5][4]['name']="cfg_filebase";
$z[6]=Array("global","",3392,3419);
$z[6][4]['name']="cfg_filebase";
$z[7]=Array("global","",8898,8925);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",9350,9379);
$z[8][4]['name']="cfg_nav_server";
$z[9]=Array("global","",10773,10802);
$z[9][4]['name']="cfg_nav_server";

?>