<?php
$z[0]=Array("global","",116,143);
$z[0][4]['name']="cfg_filebase";
$z[1]=Array("field","",331,350);
$z[1][4]['name']="path";
$z[2]=Array("global","",683,710);
$z[2][4]['name']="cfg_filebase";
$z[3]=Array("global","",1795,1824);
$z[3][4]['name']="cfg_nav_server";
$z[4]=Array("global","",2430,2459);
$z[4][4]['name']="cfg_nav_server";
$z[5]=Array("global","",2971,3000);
$z[5][4]['name']="cfg_nav_server";
$z[6]=Array("global","",3319,3348);
$z[6][4]['name']="cfg_nav_server";

?>